### PR TITLE
Replace WhatsNew file with Script

### PR DESCRIPTION
**Pull request by rnr**
PR for https://github.com/openedx/openedx-app-ios/issues/224
Page hiding is implemented as part of 'theming' 

### How to test

Clone https://github.com/edx/edx-mobile-config into the OpenEdX root folder and switch to the anton/openedX-theming branch.

From the OpenEdX root folder, run the script as:
```bash
python config_script/whitelabel.py --config-file=edx-mobile-config/openEdXAssets/whitelabel.yaml -v
```
Install on your simulator or device

The last page (Learning Site Switching) in What's New will de hidden 

Also the `process_config.py` script has been changed, it will now try to merge dictionaries from different files (e.g. iOS.yaml and shared.yaml) if both files have the same section with children in them

### CODE REVIEW

**Review by forgotvas — DISMISSED** [review]

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by touchapp** [comment]
Lets merge this if it passes

**Review by shafqat-muneer — CHANGES_REQUESTED** [review]

**Comment by shafqat-muneer** [comment]
@rnr In `whilelabel.yaml` file, if I remove all configurations and just place `whatsnew` related configuration:
```
whatsnew:
  whatsnew_import_file_path: './edx-mobile-config/openEdXAssets/WhatsNew/whats_new.json'
  project_whatsnew_file_path: './WhatsNew/WhatsNew/Data/WhatsNew.json'
```

In this case, getting following errors by running command:
```
python3 config_script/whitelabel.py --config-file=edx-mobile-config/openEdXAssets/whitelabel.yaml -v
```
Screenshot 2024-01-26 at 2 40 13 PM

**Suggestion:** I think if any configuration is not present then it's related errors should also not come.

**Comment by saeedbashir** [comment]
> Clone https://github.com/edx/edx-mobile-config into the OpenEdX root folder and switch to the anton/openedX-theming branch.

@rnr is it possible to merge this branch with `saeed/openedX` and same in the case of `yyatsenko/unit_progress` so that we don't need to switch config branches again and again for different features and everyone from `Axinite` and `Touchmedia` will have the same copy of data all the time.

**Comment by saeedbashir** [comment]
The title of the PR can be updated to `Replace WhatsNew file with Script` or something similar.

**Comment by rnr** [comment]
> > Clone https://github.com/edx/edx-mobile-config into the OpenEdX root folder and switch to the anton/openedX-theming branch.
> 
> @rnr is it possible to merge this branch with `saeed/openedX` and same in the case of `yyatsenko/unit_progress` so that we don't need to switch config branches again and again for different features and everyone from `Axinite` and `Touchmedia` will have the same copy of data all the time.

done

**Review by shafqat-muneer — APPROVED** [review]
LGTM 👍

**Pull request merged**
