### PR TITLE
fix: RTL arrowLeft in core assets

### PR DESCRIPTION
**Pull request by RawanMatar89**
### New contributor
I'm Rawan Matar, from ZeitLabs.
I start working on supporting RTL in OpenEdx iOS app, and this is the first change in my plan.

### Description
changed the direction attribute of the "arrowLeft" image in Core/Assets.

### Screenshots
| Before | After |
|--------|-------|
| IMG_3090| IMG_3087|

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @RawanMatar89! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by volodymyr-chekyrta — APPROVED** [review]
Hi @RawanMatar89, thank you for your contribution!
LGTM 👍

**Comment by openedx-webhooks** [comment]
@RawanMatar89 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-ios&entry.867055334=https://github.com/openedx/openedx-app-ios/pull/440&entry.1484655318=https://github.com/RawanMatar89&entry.752974735=2024-05-19+09:06&entry.1917517419=2024-05-22+07:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
Thanks @RawanMatar89 and @volodymyr-chekyrta!! We're looking forward for more fixes in regards to RTL and SAML.

**Pull request merged**
