### PR TITLE
fix: core data crash with inverse attribute

### PR DESCRIPTION
**Pull request by rnr**
This PR fixes crash:

IMG_7707

### CODE REVIEW

**Comment by volodymyr-chekyrta** [comment]
@IvanStepanok will review this, because deletionRule=“Cascade” was done intentionally to fix a different crash case.

**Comment by rnr** [comment]
Thank you @IvanStepanok !
I tried this and looks good. Lets wait opinion from @forgotvas (he had fixed this crash)

**Comment by forgotvas** [comment]
hi @IvanStepanok, yes main point is to add relationship between `CDPrimaryCourse` and `CDAssignment`, `Nulify` rule was committed by my fault, so our fix should work fine with `cascade` rule too. Like you suggested in your snapshot, but you did use new fields for relationship.

Can you provide example what crash fixed by `Cascade` rule?

**Comment by forgotvas** [comment]
> Hi @forgotvas
> 
> We added a cascading deletion rule to fix an issue where reloading CDPrimaryCourse did not overwrite nested objects properly. By using "Cascade," related entities (like CDAssignment) are now deleted alongside their parent, ensuring that when reloading, new data can be saved without conflicts from residual old data.

do you have steps to reproduce that crash, want to try to repeat it in my branch with my fix.

**Comment by IvanStepanok** [comment]
> do you have steps to reproduce that crash, want to try to repeat it in my branch with my fix.

As I remember, you need a really large course to reproduce this error. On the first attempt, caching works fine, but on the second time, there's a cascade of core data errors. Nothing special, the app still works, but the cache is not updated.

**Comment by rnr** [comment]
So @IvanStepanok @forgotvas 
As I see there is no difference between your fixes - just Ivan creates separate Relationships to relates entities but Vadim add `inverseEntity` field. Is this right? Then lets select one of these fixes and move forward. WDYT?

**Comment by volodymyr-chekyrta** [comment]
Please resolve git conflicts

**Comment by rnr** [comment]
Conflict is resolved
Also changed deletionRules to 'Cascade' as @IvanStepanok suggested

**Review by forgotvas — APPROVED** [review]

**Review by volodymyr-chekyrta — APPROVED** [review]
LGTM

**Pull request merged**
