### PR TITLE
fix: correct typos in localization keys, comments, and button labels

### PR DESCRIPTION
**Pull request by milad-emami**
Corrected spelling mistakes in various localization keys, comments, and button labels.

- Changed 'Comfirm' to 'Confirm' in alert titles and confirmations
- Updated localization keys:
  - 'LOGOUT_ALERT.TITLE'
  - 'DELETE_ACCOUNT.CONFIRM'
- Fixed spelling in StyledButton calls and localization fallback text
- Updated the Ukrainian translation for DELETE_ACCOUNT.CONFIRM
- Corrected comments in the codebase

These changes improve clarity and maintain consistency across the codebase.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @milad-emami! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by volodymyr-chekyrta — APPROVED** [review]
LGTM 👍

**Comment by openedx-webhooks** [comment]
@milad-emami 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-ios&entry.867055334=https://github.com/openedx/openedx-app-ios/pull/500&entry.1484655318=https://github.com/milad-emami&entry.752974735=2024-07-13+14:14&entry.1917517419=2024-07-25+07:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by volodymyr-chekyrta** [comment]
@milad-emami, thank you for your contribution!

**Pull request merged**
