### PR TITLE
docs: Update README

### PR DESCRIPTION
**Pull request by volodymyr-chekyrta**
EducationX name and URL replaced with Open edX

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @volodymyr-chekyrta! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by rnr — APPROVED** [review]

**Comment by saeedbashir** [comment]
@volodymyr-chekyrta Do we need to update the license URL or is it the correct one?
```
## License
The code in this repository is licensed under the Apache-2.0 license unless otherwise noted.

Please see [LICENSE](https://github.com/raccoongang/educationx-app-ios/blob/main/LICENSE) file for details.

**Comment by volodymyr-chekyrta** [comment]
> @volodymyr-chekyrta Do we need to update the license URL or is it the correct one?
> 
> ```
> ## License
> The code in this repository is licensed under the Apache-2.0 license unless otherwise noted.
> 
> Please see [LICENSE](https://github.com/raccoongang/educationx-app-ios/blob/main/LICENSE) file for details.
> ```

Thanks! I missed that.
Updated to the correct URL ✅

**Comment by volodymyr-chekyrta** [comment]
@saeedbashir could you please check this PR? 
Feedback has been addressed, and PR is ready for your review.

**Review by saeedbashir — APPROVED** [review]
LGTM 👍

**Comment by openedx-webhooks** [comment]
@volodymyr-chekyrta 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-ios&entry.867055334=https://github.com/openedx/openedx-app-ios/pull/327&entry.1484655318=https://github.com/volodymyr-chekyrta&entry.752974735=2024-03-07+09:24&entry.1917517419=2024-03-15+10:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
