### PR TITLE
What’s new screen (After Login Experience)

### PR DESCRIPTION
**Pull request by IvanStepanok**
Demo:

https://github.com/openedx/openedx-app-ios/assets/128456094/dfba4e01-e6e5-478f-a9f5-5b4800b8c7fa

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @IvanStepanok!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by IvanStepanok** [comment]
Demo:

https://github.com/openedx/openedx-app-ios/assets/128456094/dfba4e01-e6e5-478f-a9f5-5b4800b8c7fa

**Comment by sdaitzman** [comment]
Thank you, these screens look really great!! I only see a few very small potential changes (these are really specific, I don't think they need to be changed to move forward):

- In the Figma designs, update text is vertically snapped to the bottom, rather than the top underneath the title. I think it looks good either way here, so I just updated the Figma designs to match this.
- As the "Previous" button appears, can it fade in?

I don't think these are important enough to spend a lot of time updating, everything looks good to me! Cross-posting a similar comment here https://github.com/openedx/openedx-app-android/pull/77

**Comment by IvanStepanok** [comment]
Hi, @sdaitzman 

Thanks for your attention to detail, I was fixing it all, can you approve?

https://github.com/openedx/openedx-app-ios/assets/128456094/ad21ef7e-cf85-426b-9261-bcaa7a3062f0

**Comment by sdaitzman** [comment]
Thanks @IvanStepanok, this all looks great to me!

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@IvanStepanok 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-ios&entry.867055334=https://github.com/openedx/openedx-app-ios/pull/131&entry.1484655318=https://github.com/IvanStepanok&entry.752974735=2023-10-24+08:53&entry.1917517419=2023-10-27+11:16&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
