### PR TITLE
fix: [iOS] On Course "Home" tab the row height changes after a while #483

### PR DESCRIPTION
**Pull request by forgotvas**
[iOS] On Course "Home" tab the row height changes after a while #483

### CODE REVIEW

**Comment by saeedbashir** [comment]
@forgotvas Please update the ticket description and mention the correct issue. The issue mentioned in the description is different from the linked issues.

**Comment by forgotvas** [comment]
> @forgotvas Please update the ticket description and mention the correct issue. The issue mentioned in the description is different from the linked issues. And might need to update the PR title as well.

hi @saeedbashir, sorry, my fault, copied from another ticket. Fixed.

**Review by rnr — APPROVED** [review]

**Review by saeedbashir — APPROVED** [review]
LGTM 👍

**Comment by forgotvas** [comment]
We're closing this PR and moving these changes to our own fork, as they are critical for us. After our release, we hope to find a way to contribute these changes back, thanks!

**Pull request closed without merging**
